### ISSUE TITLE
retrieveByField cannot update records

### ISSUE THREAD

**Issue by RamonSmit** [noetix/Simple-ORM#1]
If I'm run the code underneath here, PHP gives the error: 

```
Warning: Attempt to assign property of non-object 
```

Someone got any clue how I can fix this? 
Error on this line: **$test->name = "Monique";**

```PHP
$test = Model_Test::retrieveByField('id', '5');
$test->name = "Monique";
$test->save();
```

**Comment by noetix** [comment]
It's complaining that `$test` isn't an object.

In this instance you should use `retrieveByPK` to retrieve one record by a single primary key, like so:

    $test = Model_Test::retrieveByPK(5);

The `retrieveByField` method is actually a magic method where "field" is the field you want search by, like so:

    $test = Model_Test::retrieveById(5);

However this alone isn't exactly what you're after as the `retrieveByField` field methods by default return an array of objects. You need to instruct it that you're only expecting one result, like so:

    $test = Model_Test::retrieveById(5, SimpleOrm::FETCH_ONE);

Once you have the correct record the property change and save execution should work.

**Comment by RamonSmit** [comment]
Oh @noetix, thanks for the information!
I totally overlooked that one! 

Problem solved! :+1:
