### ISSUE TITLE
Can you define Migration, Find, Custom query, relations, Joins

### ISSUE THREAD

**Issue by flik** [noetix/Simple-ORM#5]
Can you define Migration, Find, Custom query, relations, Joins ? These are all compulsory things. We are waiting for update... thanks in advance

**Comment by noetix** [comment]
This ORM does not manage migrations. The database structure and change management is yours to handle.

Finding/retrieving, including custom SQL queries are documented.

Relations (assuming you mean automatic hydration of related objects) can be implemented by writing a function within the class to call another `SimpleORM` extended class. There is no automatic understanding of your data or structure besides the basics of a table.

Joins (outside of the above) can be run via custom SQL queries as documented, and the additional properties will be assigned to the object. However, you won't be able to change any joined information.

As per the documentation, this is a very lightweight ORM and not intended to be full featured "compulsory things" you'd find in production-level frameworks like Doctrine (which I highly recommend.)
