### ISSUE TITLE
records are not saving

### ISSUE THREAD

**Issue by flik** [noetix/Simple-ORM#6]
// Define an object that relates to a table. I have table scrapped in my db
class Scrapped extends SimpleOrm { }  

 $dx['website'] = HOST;
     $dx['data'] = json_encode($data);
     
     
     $record = new Scrapped($dx);

**Comment by noetix** [comment]
You'll need to call save afterwards on the object: `$record->save()`.

Alternatively you can do `$record = new Scrapped($dx, SimpleOrm::LOAD_NEW);` to create and insert in one step.

**Comment by flik** [comment]
still having problem
data array is
Array
(
    [website] => http://www.xxxxx.com
    [data] => {"link":"http:\/\/www.xxxxx.com\/male-karachi-67345","name":"Shafi" }
)


Fatal error: Uncaught exception 'Exception' with message 'Column 'website' cannot be null INSERT INTO `admin`.`scrapped` (`website`, `data`, `created_at`) VALUES (?, ?, ?)' in C:\xampp\htdocs\xcrawler\Classes\SimpleOrm.class.php:406 Stack trace: #0 C:\xampp\htdocs\xcrawler\Classes\SimpleOrm.class.php(353): SimpleOrm->insert() #1 C:\xampp\htdocs\xcrawler\working\seeker4.php(94): SimpleOrm->save() #2 {main} thrown in C:\xampp\htdocs\xcrawler\Classes\SimpleOrm.class.php on line 406

**Comment by noetix** [comment]
Could you post some of the code in question?

The error says that the `website` property is null and your scheme doesn't allow null values in that column.

**Comment by flik** [comment]
exactly same issue with me. I am passing website with value and why is it showing this error?

// Include the SimpleOrm class
include dirname(__FILE__) . '/../Classes/SimpleOrm.class.php';
 
// Connect to the database using mysqli
$conn = new mysqli($params['database']['host'], $params['database']['user'], $params['database']['password']);

if ($conn->connect_error)
  die(sprintf('Unable to connect to the database. %s', $conn->connect_error));

// Tell SimpleOrm to use the connection you just created.
SimpleOrm::useConnection($conn, $params['database']['name']);

// Define an object that relates to a table.
class Scrapped extends SimpleOrm { }   
 $data = array('website'=>' http://www.xxxxx.com','name'=>'abcd');
$dx['website'] = HOST;
$dx['data'] = json_encode($data);

 $record = new Scrapped($dx);
     $record = new Scrapped($dx);
     $record->save();
		 debugd($record);

**Comment by noetix** [comment]
`$dx['website'] = HOST;` would evaluate to `$dx['website'] = null;`.

If you want to insert the `$data` array then you need to change what var you're building your object with.

**Comment by flik** [comment]
no. HOST is defined as constant with a name. of website. 
const HOST  = 'http://www.gxxxxxa.com';

Now I have changed the table structure from my db and resolve the above issue with set null. 

Now another issue is coming. 
It is not auto generating primary key. 
Fatal error: Uncaught exception 'Exception' with message 'Duplicate entry '0' for key 'PRIMARY' INSERT INTO `admin`.`scrapped` (`website`, `data`, `created_at`, `status`) VALUES (?, ?, ?, ?)' in C:\xampp\htdocs\xcrawler\Classes\SimpleOrm.class.php:406 Stack trace: #0 C:\xampp\htdocs\xcrawler\Classes\SimpleOrm.class.php(353): SimpleOrm->insert() #1 C:\xampp\htdocs\xcrawler\working\seeker4.php(44): SimpleOrm->save() #2 {main} thrown in C:\xampp\htdocs\xcrawler\Classes\SimpleOrm.class.php on line 406

**Comment by noetix** [comment]
This ORM does not auto-generate primary keys. It assumes your primary is `id` and auto-increments via database configuration.

**Comment by flik** [comment]
yes. Now above error also fixed with id auto increment but inserted records are null. just primary key is coming...

**Comment by noetix** [comment]
Did you end up figuring this out? I believe the issue lies within your script and not the ORM layer.
