### ISSUE TITLE
fields with ON UPDATE clause are owerwritten

### ISSUE THREAD

**Issue by joegalaxy71** [noetix/Simple-ORM#7]
it seems all record fields are written on save(), including the one that have an 'ON UPDATE' clause.

**Comment by noetix** [comment]
This class just takes the data that fits in the relevant columns and constructs the query. It does not track which columns have changed.

Feel free to submit a PR with this enhancement; I'm no longer adding new functionality.

**Comment by joegalaxy71** [comment]
Sorry didn't notice the Filters section, this will do.
