### ISSUE TITLE
Support for tables without primary key or with multi-column primary keys without auto increment

### ISSUE THREAD

**Issue by netbrothers-tr** [noetix/Simple-ORM#8]
First of all thanks for this very handy library!

I'm receiving this error on an insert: `record not found in database. (PK: 5)`. This seems to be the case because the table has a multi-column primary key without auto increment. I want to set the value, because it's not an auto increment column but I can't set the value, because it will produce the above error.

So, here go my questions:

Does Simple ORM always require a primary key?
Does Simple ORM always require a single column primary key?
Does Simple ORM always require an auto increment primary key?

**Comment by noetix** [comment]
It requires a single column primary key.

You can specify what you want for the ID so you don't have to use auto increment.

See https://github.com/noetix/Simple-ORM/blob/master/SimpleOrm.class.php#L27
